# fly.toml app configuration file generated for private-network-router on 2025-05-16T12:21:37-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'private-network-router'
primary_region = 'atl'

[build]

[http_service]
  internal_port = 3004

[[services]]
  protocol = 'tcp'
  internal_port = 3004
  processes = ['app']

  [[services.ports]]
    port = 3004
    handlers = ['http']

  [[services.ports]]
    port = 8080
    handlers = ['http']

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
